### PR TITLE
Try testing LLVM 15 on linux

### PR DESCRIPTION
**Pull request by dmlloyd**

### CODE REVIEW

**Comment by dmlloyd** [comment]
🤷🏻 I'll leave this here for revisiting later.

**Comment by dgrove-oss** [comment]
Maybe we need to wait for a new release of the GitHub action to install llvm?

**Comment by dmlloyd** [comment]
Yeah I tried updating to the latest but it still wasn't working.

**Comment by dmlloyd** [comment]
It works now ✅

**Review by dgrove-oss — APPROVED** [review]

**Pull request merged**
