### PR TITLE
restore java.lang.Object.toString non-native implementation

### PR DESCRIPTION
**Pull request by dgrove-oss**

### CODE REVIEW

**Comment by dgrove-oss** [comment]
This adds 4MB to the "hello world" executable.  

Need to measure to see if #8 is significantly smaller.

**Review by dmlloyd — APPROVED** [review]
FWIW the change looks OK to me.

**Comment by dgrove-oss** [comment]
It turns out that just defining `Object.toString()` to be anything non-native results in a 4MB increase in executable size (even something trivial like `return "anObject";`.  This seems like pretty strong evidence that RTA is getting confused with method hierarchies containing native methods.   I should probably debug that at some point, but independent of that problem we should go ahead and merge this PR to hopefully unblock @michihirohorie on https://github.com/qbicc/qbicc/issues/636

**Comment by dmlloyd** [comment]
Sounds good, done.

**Pull request merged**
